server:
  port: 0
spring:
  boot:
    admin:
      client:
        url: http://localhost:8887/
        instance:
          prefer-ip: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"