server:
  port: 0
spring:
  application:
    name: item-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${spring.application.instance.id:${random.int}}
        health-check-interval: 1s
        health-check-critical-timeout: 1s
