spring:
  profiles:
    active: dev
  application:
    name: user-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      token: springcloud
server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: "*"
