spring:
  datasource:
    url: jdbc:mysql://mysql/spring-shop
    username: spring_rw
    password: (^pass$W0rd..
logging:
  level:
    root: warn
server:
  port: 8443
  ssl:
    key-store: classpath:spring-shop.jks
    key-store-password: spring
    key-password: spring