debug: false
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#
# https://docs.spring.io/spring-boot/docs/2.1.18.RELEASE/reference/html/howto-database-initialization.html
#
# In a JPA-based app, you can choose to let Hibernate create the schema or use schema.sql,
# but you cannot do both. Make sure to disable spring.jpa.hibernate.ddl-auto if you use schema.sql.
#
    hibernate:
      ddl-auto: none
  datasource:
    schema: classpath:/database/schema.sql
    data: classpath:/database/data.sql
    initialization-mode: always
    url: jdbc:h2:mem:spring_shop
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        security: debug
shop:
  server:
    listen: server listen on :${server.port}
  pagination:
    size: 15
